name: CI

on: 
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: pnpm run lint

      - name: Run TypeCheck
        run: pnpm run typecheck
